[build-system]
requires = [
    "setuptools >= 40.9.0",
]
build-backend = "setuptools.build_meta"

[project]
name = "bllose_config_model"
version = "0.0.1"
dependencies = [
    'importlib-metadata; python_version<"3.12"'
]