[build-system]
requires = [
    "setuptools >= 40.9.0",
]
build-backend = "setuptools.build_meta"

[project]
name = "bllose_config_model"
version = "0.0.2"
dependencies = [
    'importlib-metadata; python_version<"3.12"',
    "javaproperties == 0.8.1",
    "PyYAML== 6.0.2"
]